networks:
  capec-network:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: src/docker-files/Dockerfile.server
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - capec-network
    hostname: rag-server
    volumes:
      - ./src/index/index/:/app/src/index/index/
    environment:
      - TOKENIZERS_PARALLELISM=false

  client:
    build:
      context: .
      dockerfile: src/docker-files/Dockerfile.client
    networks:
      - capec-network
    ports:
      - "127.0.0.1:7860:7860"
    environment:
      - SERVER_HOST=rag-server
      - SERVER_PORT=8000

  qdrant:
    image: qdrant/qdrant:v0.10.1
    ports:
      - "127.0.0.1:6333:6333"
      - "127.0.0.1:6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - capec-network
    hostname: qdrant

volumes:
  qdrant_storage:
    driver: local
